## Objective:
### The objective of this assignment is “Building a repository of universities of UK”

In [59]:
#Importing Necessary Libraries
from bs4 import BeautifulSoup as soup
import requests
import lxml
import re
import pandas as pd
from threading import Thread
from elasticsearch import Elasticsearch

### Extracting details from main website

In [60]:
main_url='https://en.wikipedia.org/wiki/List_of_universities_in_England'
source=requests.get(my_url).text
page_soup=soup(source,'lxml')
containers=page_soup.find('div',{'class':"mw-parser-output"})
rows= containers.table.find_all('tr') 
data=[]
header_name=[]
x=0
type_name=re.split('https://en.wikipedia.org/wiki/',my_url)[1]
# csv_file=open(csv_name[1],'w')

for row in rows:
    x+=1
    if x==1:
        header=row.find_all('th')
        for hedr in header:
            header_name.append(hedr.text[0:-1])
        header_name.append('Url')
        data.append(header_name)
    else:
        cols = row.find_all('td')
        link='https://en.wikipedia.org'+cols[0].a.get('href')
        cols = [ele.text.strip() for ele in cols]
        cols.append(link)
        data.append([ele for ele in cols if ele])

df = pd.DataFrame.from_records(data[1:], columns=data[0])
urls=list(df['Url'])

df

,University,Location,Established,Number of students,Tuition fee,Degree powers,Url
0,AECC University College,Bournemouth,– (1965),-,"£9,250",Taught,https://en.wikipedia.org/wiki/Anglo-European_C...
1,Anglia Ruskin University,"Cambridge, Chelmsford, Peterborough",1992 (1858),"24,490","£9,250",Full,https://en.wikipedia.org/wiki/Anglia_Ruskin_Un...
2,Arden University,Coventry (distance learning),2015 (1990),"8,000[7]",- (private),Taught,https://en.wikipedia.org/wiki/Arden_University
3,Arts University Bournemouth,Poole,2012 (1885),"3,385","£9,250",Taught,https://en.wikipedia.org/wiki/Arts_University_...
4,University of the Arts London,London,2004,"19,095","£9,250",Full,https://en.wikipedia.org/wiki/University_of_th...
...,...,...,...,...,...,...,...
125,University of Wolverhampton,"Burton, Telford, Walsall, Wolverhampton",1992 (1969),"19,045","£9,250[15]",Full,https://en.wikipedia.org/wiki/University_of_Wo...
126,University of Worcester,Worcester,1997,"10,075","£9,250",Full,https://en.wikipedia.org/wiki/University_of_Wo...
127,Writtle University College,Chelmsford,– (1893),750,"£9,250",Taught,https://en.wikipedia.org/wiki/Writtle_Universi...
128,University of York,York,1963,"19,470","£9,250",Full,https://en.wikipedia.org/wiki/University_of_York
129,York St John University,York,2006 (1841),"6,620","£9,250",Full,https://en.wikipedia.org/wiki/York_St_John_Uni...

### Extracting details from individual university website

In [61]:
sub_agg_df = pd.DataFrame(columns=['University','Former names','Detailed_Location','Students','Undergraduates','Postgraduates','Url'])
print(sub_agg_df)

# defining the function for scraping individual website 
def sub_scrapping(url,indx,U_name):
    print(url,indx)
    my_url=url
    try:
        print('Executing for '+my_url)
        source=requests.get(my_url).text
        page_soup=soup(source,'lxml')
        containers=page_soup.find('table',{'class':"infobox vcard"})
        indivual_data={}
        sub_headers=['Former names','Location','Students','Undergraduates','Postgraduates']

        for sh in range(1,6):
            sub_container=containers.find_all('tr')
            for ele in sub_container:
                try:
                    if ele.th.text==sub_headers[sh-1]:
                        indivual_data.update({sub_headers[sh-1]:ele.td.text})
                except:
                    pass
            if len(indivual_data) < sh:
                indivual_data.update({sub_headers[sh-1]:None})


        df_sub=pd.DataFrame([[U_name,indivual_data['Former names'],str(indivual_data['Location']),indivual_data['Students'],indivual_data['Undergraduates'],indivual_data['Postgraduates'],my_url]],columns=['University','Former names','Detailed_Location','Students','Undergraduates','Postgraduates','Url'],index=[indx])
        global sub_agg_df
        sub_agg_df=sub_agg_df.append(df_sub)
    except:
        print('Error in fetching url '+my_url)

Empty DataFrame
Columns: [University, Former names, Detailed_Location, Students, Undergraduates, Postgraduates, Url]
Index: []

### Creating the Thread for parallel processing.

In [62]:
threadlist=[]
for x in df.itertuples():
    td= Thread(target=sub_scrapping,args=(x.Url,x.Index,x.University))
    td.start()
    threadlist.append(td)
for b in threadlist:
    b.join()
sub_agg_df

https://en.wikipedia.org/wiki/Anglo-European_College_of_Chiropractichttps://en.wikipedia.org/wiki/Anglia_Ruskin_University 1
Executing for https://en.wikipedia.org/wiki/Anglia_Ruskin_University
https://en.wikipedia.org/wiki/Arden_University 2
Executing for https://en.wikipedia.org/wiki/Arden_University
 https://en.wikipedia.org/wiki/Arts_University_Bournemouth0
Executing for https://en.wikipedia.org/wiki/Anglo-European_College_of_Chiropractic
3
Executing for https://en.wikipedia.org/wiki/Arts_University_Bournemouth
https://en.wikipedia.org/wiki/University_of_the_Arts_London 4
Executing for https://en.wikipedia.org/wiki/University_of_the_Arts_London
https://en.wikipedia.org/wiki/Aston_University 5https://en.wikipedia.org/wiki/University_of_Bath
 https://en.wikipedia.org/wiki/Bath_Spa_University 7
Executing for https://en.wikipedia.org/wiki/Bath_Spa_University
Executing for https://en.wikipedia.org/wiki/Aston_University6https://en.wikipedia.org/wiki/University_of_Bedfordshire
Executing for https://en.wikipedia.org/wiki/University_of_Bath

https://en.wikipedia.org/wiki/University_of_Birmingham8 https://en.wikipedia.org/wiki/University_College_Birmingham 10
Executing for https://en.wikipedia.org/wiki/University_College_Birminghamhttps://en.wikipedia.org/wiki/Birmingham_City_University

11Executing for https://en.wikipedia.org/wiki/University_of_Bedfordshire9
https://en.wikipedia.org/wiki/Bishop_Grosseteste_University 12
Executing for https://en.wikipedia.org/wiki/Bishop_Grosseteste_University
Executing for https://en.wikipedia.org/wiki/Birmingham_City_University

Executing for https://en.wikipedia.org/wiki/University_of_Birmingham
https://en.wikipedia.org/wiki/University_of_Bolton 13
Executing for https://en.wikipedia.org/wiki/University_of_Bolton

https://en.wikipedia.org/wiki/Bournemouth_University 14https://en.wikipedia.org/wiki/BPP_University 15
Executing for https://en.wikipedia.org/wiki/BPP_University

https://en.wikipedia.org/wiki/University_of_Bradford 16
Executing for https://en.wikipedia.org/wiki/University_of_Bradford
Executing for https://en.wikipedia.org/wiki/Bournemouth_University
https://en.wikipedia.org/wiki/University_of_Brighton 17
Executing for https://en.wikipedia.org/wiki/University_of_Brighton
https://en.wikipedia.org/wiki/University_of_Bristol https://en.wikipedia.org/wiki/Brunel_University_London 19
Executing for https://en.wikipedia.org/wiki/Brunel_University_London
18
https://en.wikipedia.org/wiki/University_of_BuckinghamExecuting for https://en.wikipedia.org/wiki/University_of_Bristol
https://en.wikipedia.org/wiki/Buckinghamshire_New_University 21
Executing for https://en.wikipedia.org/wiki/Buckinghamshire_New_University
20
Executing for https://en.wikipedia.org/wiki/University_of_Buckinghamhttps://en.wikipedia.org/wiki/University_of_Cambridge 22
Executing for https://en.wikipedia.org/wiki/University_of_Cambridge

https://en.wikipedia.org/wiki/Canterbury_Christ_Church_University 23
Executing for https://en.wikipedia.org/wiki/Canterbury_Christ_Church_University
https://en.wikipedia.org/wiki/University_of_Central_Lancashire 24
Executing for https://en.wikipedia.org/wiki/University_of_Central_Lancashire
https://en.wikipedia.org/wiki/University_of_Chester 25
Executing for https://en.wikipedia.org/wiki/University_of_Chester
https://en.wikipedia.org/wiki/University_of_Chichester 26
https://en.wikipedia.org/wiki/Coventry_University 27
Executing for https://en.wikipedia.org/wiki/Coventry_University
Executing for https://en.wikipedia.org/wiki/University_of_Chichester
https://en.wikipedia.org/wiki/Cranfield_University 28
Executing for https://en.wikipedia.org/wiki/Cranfield_University
https://en.wikipedia.org/wiki/University_for_the_Creative_Arts https://en.wikipedia.org/wiki/University_of_Cumbria 30
Executing for https://en.wikipedia.org/wiki/University_of_Cumbria
29
Executing for https://en.wikipedia.org/wiki/University_for_the_Creative_Arts
https://en.wikipedia.org/wiki/De_Montfort_Universityhttps://en.wikipedia.org/wiki/University_of_Derby 31
Executing for https://en.wikipedia.org/wiki/De_Montfort_University
https://en.wikipedia.org/wiki/Durham_University 33
Executing for https://en.wikipedia.org/wiki/Durham_University
 32
Executing for https://en.wikipedia.org/wiki/University_of_Derby
https://en.wikipedia.org/wiki/University_of_East_Anglia 34https://en.wikipedia.org/wiki/University_of_East_London 35
Executing for https://en.wikipedia.org/wiki/University_of_East_London

Executing for https://en.wikipedia.org/wiki/University_of_East_Angliahttps://en.wikipedia.org/wiki/Edge_Hill_University 36
Executing for https://en.wikipedia.org/wiki/Edge_Hill_University
https://en.wikipedia.org/wiki/University_of_Essex 37

Executing for https://en.wikipedia.org/wiki/University_of_Essex
https://en.wikipedia.org/wiki/College_of_Estate_Management https://en.wikipedia.org/wiki/University_of_Exeter 39
Executing for https://en.wikipedia.org/wiki/University_of_Exeter
38https://en.wikipedia.org/wiki/Falmouth_University
40https://en.wikipedia.org/wiki/University_of_Gloucestershire 41
Executing for https://en.wikipedia.org/wiki/University_of_Gloucestershire

Executing for https://en.wikipedia.org/wiki/College_of_Estate_Managementhttps://en.wikipedia.org/wiki/University_of_Greenwich 42https://en.wikipedia.org/wiki/Harper_Adams_University 43
Executing for https://en.wikipedia.org/wiki/Falmouth_University
NoneExecuting for https://en.wikipedia.org/wiki/Harper_Adams_University


 Executing for https://en.wikipedia.org/wiki/University_of_Greenwichhttps://en.wikipedia.org/wiki/University_of_Hertfordshire44
 45
Executing for https://en.wikipedia.org/wiki/University_of_Hertfordshire
https://en.wikipedia.org/wiki/University_of_Huddersfield
 46
Executing for https://en.wikipedia.org/wiki/University_of_Huddersfield

Exception in thread Thread-180:
Traceback (most recent call last):
  File "<ipython-input-61-37a5cedd733b>", line 9, in sub_scrapping
    print('Executing for '+my_url)
TypeError: can only concatenate str (not "NoneType") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\akhil\anaconda3\envs\webscrapping\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\akhil\anaconda3\envs\webscrapping\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-61-37a5cedd733b>", line 32, in sub_scrapping
    print('Error in fetching url '+my_url)
TypeError: can only concatenate str (not "NoneType") to str

https://en.wikipedia.org/wiki/University_of_Hull 47
Executing for https://en.wikipedia.org/wiki/University_of_Hull
https://en.wikipedia.org/wiki/Imperial_College_London 48https://en.wikipedia.org/wiki/Keele_University 49
Executing for https://en.wikipedia.org/wiki/Keele_University
https://en.wikipedia.org/wiki/University_of_Kent 50
Executing for https://en.wikipedia.org/wiki/University_of_Kent

Executing for https://en.wikipedia.org/wiki/Imperial_College_London
https://en.wikipedia.org/wiki/Kingston_University 51
Executing for https://en.wikipedia.org/wiki/Kingston_University
https://en.wikipedia.org/wiki/Lancaster_University 52
Executing for https://en.wikipedia.org/wiki/Lancaster_University
https://en.wikipedia.org/wiki/University_of_Law 53
Executing for https://en.wikipedia.org/wiki/University_of_Law
https://en.wikipedia.org/wiki/University_of_Leeds 54
Executing for https://en.wikipedia.org/wiki/University_of_Leeds
None 55
https://en.wikipedia.org/wiki/Leeds_Beckett_University 56https://en.wikipedia.org/wiki/Leeds_Trinity_University 57
Executing for https://en.wikipedia.org/wiki/Leeds_Trinity_University

Executing for https://en.wikipedia.org/wiki/Leeds_Beckett_University
https://en.wikipedia.org/wiki/University_of_Leicester 58
Executing for https://en.wikipedia.org/wiki/University_of_Leicester
https://en.wikipedia.org/wiki/University_of_Lincoln 59
Executing for https://en.wikipedia.org/wiki/University_of_Lincoln
https://en.wikipedia.org/wiki/University_of_Liverpool 60
Executing for https://en.wikipedia.org/wiki/University_of_Liverpool
https://en.wikipedia.org/wiki/Liverpool_Hope_University 61
Executing for https://en.wikipedia.org/wiki/Liverpool_Hope_University
https://en.wikipedia.org/wiki/Liverpool_John_Moores_University https://en.wikipedia.org/wiki/University_of_London 63
Executing for https://en.wikipedia.org/wiki/University_of_London
62
Executing for https://en.wikipedia.org/wiki/Liverpool_John_Moores_University
https://en.wikipedia.org/wiki/University_of_London 64https://en.wikipedia.org/wiki/University_of_London 65
Executing for https://en.wikipedia.org/wiki/University_of_London

Executing for https://en.wikipedia.org/wiki/University_of_London
https://en.wikipedia.org/wiki/University_of_Londonhttps://en.wikipedia.org/wiki/University_of_London 67
Executing for https://en.wikipedia.org/wiki/University_of_London
 https://en.wikipedia.org/wiki/University_of_London 68
Executing for https://en.wikipedia.org/wiki/University_of_London
66https://en.wikipedia.org/wiki/University_of_London 69
Executing for https://en.wikipedia.org/wiki/University_of_London

Executing for https://en.wikipedia.org/wiki/University_of_London
https://en.wikipedia.org/wiki/University_of_London https://en.wikipedia.org/wiki/University_of_London70

Exception in thread Thread-191:
Traceback (most recent call last):
  File "<ipython-input-61-37a5cedd733b>", line 9, in sub_scrapping
    print('Executing for '+my_url)
TypeError: can only concatenate str (not "NoneType") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\akhil\anaconda3\envs\webscrapping\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\akhil\anaconda3\envs\webscrapping\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-61-37a5cedd733b>", line 32, in sub_scrapping
    print('Error in fetching url '+my_url)
TypeError: can only concatenate str (not "NoneType") to str

 Executing for https://en.wikipedia.org/wiki/University_of_London71
Executing for https://en.wikipedia.org/wiki/University_of_London

https://en.wikipedia.org/wiki/University_of_London 72
Executing for https://en.wikipedia.org/wiki/University_of_London
https://en.wikipedia.org/wiki/University_of_London https://en.wikipedia.org/wiki/University_of_London 74
Executing for https://en.wikipedia.org/wiki/University_of_London
73
Executing for https://en.wikipedia.org/wiki/University_of_London
https://en.wikipedia.org/wiki/University_of_London 75
Executing for https://en.wikipedia.org/wiki/University_of_London
https://en.wikipedia.org/wiki/University_of_London https://en.wikipedia.org/wiki/University_of_London76 77
Executing for https://en.wikipedia.org/wiki/University_of_London

https://en.wikipedia.org/wiki/University_of_London 78
Executing for https://en.wikipedia.org/wiki/University_of_London
Executing for https://en.wikipedia.org/wiki/University_of_London
https://en.wikipedia.org/wiki/University_of_London https://en.wikipedia.org/wiki/University_of_London 80
Executing for https://en.wikipedia.org/wiki/University_of_London
79
Executing for https://en.wikipedia.org/wiki/University_of_London
https://en.wikipedia.org/wiki/University_of_London 81
Executing for https://en.wikipedia.org/wiki/University_of_London
https://en.wikipedia.org/wiki/The_London_Institute_of_Banking_%26_Finance 82
Executing for https://en.wikipedia.org/wiki/The_London_Institute_of_Banking_%26_Finance
https://en.wikipedia.org/wiki/London_Metropolitan_University 83https://en.wikipedia.org/wiki/London_South_Bank_University
https://en.wikipedia.org/wiki/Loughborough_UniversityExecuting for https://en.wikipedia.org/wiki/London_Metropolitan_University
84 85
Executing for https://en.wikipedia.org/wiki/Loughborough_University

Executing for https://en.wikipedia.org/wiki/London_South_Bank_University
https://en.wikipedia.org/wiki/University_of_Manchester 86
Executing for https://en.wikipedia.org/wiki/University_of_Manchester
https://en.wikipedia.org/wiki/Manchester_Metropolitan_University 87
Executing for https://en.wikipedia.org/wiki/Manchester_Metropolitan_University
https://en.wikipedia.org/wiki/Middlesex_University 88
Executing for https://en.wikipedia.org/wiki/Middlesex_University
https://en.wikipedia.org/wiki/Newcastle_Universityhttps://en.wikipedia.org/wiki/Newman_University,_Birmingham 89
Executing for https://en.wikipedia.org/wiki/Newcastle_University
https://en.wikipedia.org/wiki/University_of_Northampton  91
Executing for https://en.wikipedia.org/wiki/University_of_Northampton
https://en.wikipedia.org/wiki/Northumbria_University 92
Executing for https://en.wikipedia.org/wiki/Northumbria_University
90
Executing for https://en.wikipedia.org/wiki/Newman_University,_Birmingham
https://en.wikipedia.org/wiki/Norwich_University_of_the_Arts 93
Executing for https://en.wikipedia.org/wiki/Norwich_University_of_the_Arts
https://en.wikipedia.org/wiki/University_of_Nottingham 94
Executing for https://en.wikipedia.org/wiki/University_of_Nottingham
https://en.wikipedia.org/wiki/Nottingham_Trent_University 95
Executing for https://en.wikipedia.org/wiki/Nottingham_Trent_University
https://en.wikipedia.org/wiki/Open_University 96
Executing for https://en.wikipedia.org/wiki/Open_University
https://en.wikipedia.org/wiki/University_College_of_Osteopathy 97https://en.wikipedia.org/wiki/University_of_Oxford
 98
Executing for https://en.wikipedia.org/wiki/University_of_Oxford
Executing for https://en.wikipedia.org/wiki/University_College_of_Osteopathy
https://en.wikipedia.org/wiki/Oxford_Brookes_University 99
Executing for https://en.wikipedia.org/wiki/Oxford_Brookes_University
https://en.wikipedia.org/wiki/Plymouth_Universityhttps://en.wikipedia.org/wiki/University_of_Portsmouth 100https://en.wikipedia.org/wiki/Ravensbourne_(college)  102
Executing for https://en.wikipedia.org/wiki/Ravensbourne_(college)
https://en.wikipedia.org/wiki/University_of_Reading101
 103
Executing for https://en.wikipedia.org/wiki/University_of_Reading

Executing for https://en.wikipedia.org/wiki/University_of_Portsmouth
https://en.wikipedia.org/wiki/Regent%27s_University_London Executing for https://en.wikipedia.org/wiki/Plymouth_University104

Executing for https://en.wikipedia.org/wiki/Regent%27s_University_London
https://en.wikipedia.org/wiki/Roehampton_University 105https://en.wikipedia.org/wiki/Royal_Agricultural_University
Executing for https://en.wikipedia.org/wiki/Roehampton_University
 106
Executing for https://en.wikipedia.org/wiki/Royal_Agricultural_University
https://en.wikipedia.org/wiki/University_of_Salford 107
Executing for https://en.wikipedia.org/wiki/University_of_Salford
https://en.wikipedia.org/wiki/University_of_Sheffield 108
Executing for https://en.wikipedia.org/wiki/University_of_Sheffield
https://en.wikipedia.org/wiki/Sheffield_Hallam_University 109
Executing for https://en.wikipedia.org/wiki/Sheffield_Hallam_University
https://en.wikipedia.org/wiki/University_of_Southampton 110
Executing for https://en.wikipedia.org/wiki/University_of_Southampton
https://en.wikipedia.org/wiki/Southampton_Solent_University https://en.wikipedia.org/wiki/University_of_St_Mark_%26_St_John 112
Executing for https://en.wikipedia.org/wiki/University_of_St_Mark_%26_St_John
111
Executing for https://en.wikipedia.org/wiki/Southampton_Solent_University
https://en.wikipedia.org/wiki/St_Mary%27s_University,_Twickenham 113
Executing for https://en.wikipedia.org/wiki/St_Mary%27s_University,_Twickenham
https://en.wikipedia.org/wiki/Staffordshire_University 114
Executing for https://en.wikipedia.org/wiki/Staffordshire_University
https://en.wikipedia.org/wiki/University_of_Suffolk 115
Executing for https://en.wikipedia.org/wiki/University_of_Suffolk
https://en.wikipedia.org/wiki/University_of_Sunderland 116
Executing for https://en.wikipedia.org/wiki/University_of_Sunderland
https://en.wikipedia.org/wiki/University_of_Surrey 117https://en.wikipedia.org/wiki/University_of_Sussex 118
Executing for https://en.wikipedia.org/wiki/University_of_Sussex

Executing for https://en.wikipedia.org/wiki/University_of_Surrey
https://en.wikipedia.org/wiki/Teesside_University https://en.wikipedia.org/wiki/University_of_Warwick 120
Executing for https://en.wikipedia.org/wiki/University_of_Warwick
119
Executing for https://en.wikipedia.org/wiki/Teesside_University
https://en.wikipedia.org/wiki/University_of_West_London 121
Executing for https://en.wikipedia.org/wiki/University_of_West_London
https://en.wikipedia.org/wiki/University_of_the_West_of_England 122
Executing for https://en.wikipedia.org/wiki/University_of_the_West_of_England
https://en.wikipedia.org/wiki/University_of_Westminster 123
Executing for https://en.wikipedia.org/wiki/University_of_Westminster
https://en.wikipedia.org/wiki/University_of_Winchester 124
Executing for https://en.wikipedia.org/wiki/University_of_Winchesterhttps://en.wikipedia.org/wiki/University_of_Wolverhampton 125
Executing for https://en.wikipedia.org/wiki/University_of_Wolverhampton

https://en.wikipedia.org/wiki/University_of_Worcester 126
Executing for https://en.wikipedia.org/wiki/University_of_Worcester
https://en.wikipedia.org/wiki/Writtle_University_College 127
Executing for https://en.wikipedia.org/wiki/Writtle_University_College
https://en.wikipedia.org/wiki/University_of_York 128
Executing for https://en.wikipedia.org/wiki/University_of_York
https://en.wikipedia.org/wiki/York_St_John_University 129
Executing for https://en.wikipedia.org/wiki/York_St_John_University
Error in fetching url https://en.wikipedia.org/wiki/College_of_Estate_Management

,University,Former names,Detailed_Location,Students,Undergraduates,Postgraduates,Url
2,Arden University,None,"Coventry, UK",None,None,None,https://en.wikipedia.org/wiki/Arden_University
0,AECC University College,None,"Bournemouth, Dorset, England50°43′38″N 1°49′44...",None,470,265,https://en.wikipedia.org/wiki/Anglo-European_C...
15,BPP University,BPP Law School (1992)BPP College of Profession...,"Abingdon, Birmingham, Bristol, Cambridge, Leed...","16,000",None,None,https://en.wikipedia.org/wiki/BPP_University
10,University College Birmingham[Note 3],None,"Birmingham, United Kingdom","4,905 HE (2018/19)[1]","4,415 (2018/19)[1]",485 (2018/19)[1],https://en.wikipedia.org/wiki/University_Colle...
12,Bishop Grosseteste University,Diocesan Training School for MistressesLincoln...,"Lincoln, Lincolnshire, EnglandCoordinates: 53°...","2,260 (2018/19)[2]","1,665 (2018/19)[2]",595 (2018/19)[2],https://en.wikipedia.org/wiki/Bishop_Grossetes...
...,...,...,...,...,...,...,...
33,Durham University,None,"Durham and Stockton-on-Tees, England","19,025 (2018/19)[3]","14,320 (2018/19)[3]","4,705 (2018/19)[3]",https://en.wikipedia.org/wiki/Durham_University
9,University of Birmingham,None,"Birmingham, West Midlands, United Kingdom52°27...","35,445 (2018/19)[6]","22,940 (2018/19)[6]","12,505 (2018/19)[6]",https://en.wikipedia.org/wiki/University_of_Bi...
22,University of Cambridge,None,"Cambridge, England, United Kingdom","23,247 (2019)[7]","12,354 (2019)","10,893 (2019)",https://en.wikipedia.org/wiki/University_of_Ca...
110,University of Southampton,None,"Southampton, United Kingdom","22,715 (2018/19)[3]","15,790 (2018/19)[3]","6,925 (2018/19)[3]",https://en.wikipedia.org/wiki/University_of_So...
98,University of Oxford,None,"Oxford, England, United Kingdom","24,515 (2019) [7]","11,955","12,010",https://en.wikipedia.org/wiki/University_of_Ox...

### Final adjustment by joinging the sub table with sub table

In [63]:
df.drop('Url', axis=1, inplace=True)
final_df=pd.merge(sub_agg_df, df, on='University')
final_df

,University,Former names,Detailed_Location,Students,Undergraduates,Postgraduates,Url,Location,Established,Number of students,Tuition fee,Degree powers
0,Arden University,None,"Coventry, UK",None,None,None,https://en.wikipedia.org/wiki/Arden_University,Coventry (distance learning),2015 (1990),"8,000[7]",- (private),Taught
1,AECC University College,None,"Bournemouth, Dorset, England50°43′38″N 1°49′44...",None,470,265,https://en.wikipedia.org/wiki/Anglo-European_C...,Bournemouth,– (1965),-,"£9,250",Taught
2,BPP University,BPP Law School (1992)BPP College of Profession...,"Abingdon, Birmingham, Bristol, Cambridge, Leed...","16,000",None,None,https://en.wikipedia.org/wiki/BPP_University,"Abingdon, Birmingham, Bristol, Cambridge, Leed...",2013 (1992),"6,780[9]",- (private),Taught
3,University College Birmingham[Note 3],None,"Birmingham, United Kingdom","4,905 HE (2018/19)[1]","4,415 (2018/19)[1]",485 (2018/19)[1],https://en.wikipedia.org/wiki/University_Colle...,Birmingham,2012 (1957),"4,905","£9,076[8]",Taught
4,Bishop Grosseteste University,Diocesan Training School for MistressesLincoln...,"Lincoln, Lincolnshire, EnglandCoordinates: 53°...","2,260 (2018/19)[2]","1,665 (2018/19)[2]",595 (2018/19)[2],https://en.wikipedia.org/wiki/Bishop_Grossetes...,Lincoln,2012 (1862),"2,260","£9,250",Taught
...,...,...,...,...,...,...,...,...,...,...,...,...
122,Durham University,None,"Durham and Stockton-on-Tees, England","19,025 (2018/19)[3]","14,320 (2018/19)[3]","4,705 (2018/19)[3]",https://en.wikipedia.org/wiki/Durham_University,"Durham, Stockton",1832,"19,025","£9,250",Full
123,University of Birmingham,None,"Birmingham, West Midlands, United Kingdom52°27...","35,445 (2018/19)[6]","22,940 (2018/19)[6]","12,505 (2018/19)[6]",https://en.wikipedia.org/wiki/University_of_Bi...,Birmingham,1900,"35,445","£9,250",Full
124,University of Cambridge,None,"Cambridge, England, United Kingdom","23,247 (2019)[7]","12,354 (2019)","10,893 (2019)",https://en.wikipedia.org/wiki/University_of_Ca...,Cambridge,1209,"20,890","£9,250",Full
125,University of Southampton,None,"Southampton, United Kingdom","22,715 (2018/19)[3]","15,790 (2018/19)[3]","6,925 (2018/19)[3]",https://en.wikipedia.org/wiki/University_of_So...,Southampton,1952 (1902),"22,715","£9,250",Full
126,University of Oxford,None,"Oxford, England, United Kingdom","24,515 (2019) [7]","11,955","12,010",https://en.wikipedia.org/wiki/University_of_Ox...,Oxford,1096,"25,390","£9,250",Full

In [64]:
# Optional: Saving the table in CSV format for analysis purspose in excel:
final_df.to_csv(type_name+'.csv')

In [65]:
es= Elasticsearch('http://localhost:9200')
es.indices.delete(index='universities')
es.indices.create(index='universities',ignore=400)
for x in final_df.iterrows():
    es.index(index='universities',doc_type=type_name,id=x[0] ,body=dict(x[1]))
print('!!!!!!!!----Data Transfer Completed-----!!!!!!!')

C:\Users\akhil\anaconda3\envs\webscrapping\lib\site-packages\ipykernel_launcher.py:5: ElasticsearchDeprecationWarning: [types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).
  """

!!!!!!!!----Data Transfer Completed-----!!!!!!!

### Check one query whether the documents are inserted or not.

In [66]:
es= Elasticsearch('http://localhost:9200')
res=es.search(index='universities',body={"from":0, "size":1,"query":{"match":{"University":"Harper Adams University"}}})
res

{'took': 713,
 'timed_out': False,
 '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0},
 'hits': {'total': {'value': 125, 'relation': 'eq'},
  'max_score': 9.631557,
  'hits': [{'_index': 'universities',
    '_type': 'List_of_universities_in_England',
    '_id': '26',
    '_score': 9.631557,
    '_source': {'University': 'Harper Adams University',
     'Former names': None,
     'Detailed_Location': 'Edgmond, Shropshire, TF10 8NB, United Kingdom52°46′47″N 2°25′39″W\ufeff / \ufeff52.779651°N 2.427517°W\ufeff / 52.779651; -2.427517',
     'Students': '5,375 (2018/19)[1]',
     'Undergraduates': '4,740 (2018/19)[1]',
     'Postgraduates': '635 (2018/19)[1]',
     'Url': 'https://en.wikipedia.org/wiki/Harper_Adams_University',
     'Location': 'Edgmond',
     'Established': '2012 (1901)',
     'Number of students': '5,375',
     'Tuition fee': '£9,250',
     'Degree powers': 'Full'}}]}}

### Optimize search which includes both current name and former names of university:

In [67]:

res=es.search(index="universities",body={"from":0, "size":2, "query":{"bool":{"must":{"match":{"University":"Harper Adams University"}},"must":{"match":{"Former names":"None"}}}}})           
res

{'took': 1,
 'timed_out': False,
 '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0},
 'hits': {'total': {'value': 0, 'relation': 'eq'},
  'max_score': None,
  'hits': []}}

### Since the parse data need more cleaning before it pass to ElasticSearch engine. The schema should be in following format in production ready environment:

In [ ]:

{
    "settings":{
        "analysis":{
            "analyzer":{
                "my_analyzer":{
                    "type":"keyword",
                }
            }
        }
    }

    "mappings":{
        "doc":{
            "dynamic": "strict",
            "properties":{
                "University":{
                    "type":"text",
                    "fields":{
                        "keyword":{
                            "type":"keyword"
                        }
                    },
                    "analyzer":"my_analyzer"
                },
                "Former names":{
                    "type":"text",
                    "fields":{
                        "keyword":{
                            "type":"keyword"
                        }
                    },
                    "analyzer":"my_analyzer"
                },
                "Detailed_Location":{
                    "type":"text",
                    "fields":{
                        "keyword":{
                            "type":"keyword"
                        }
                    },
                    "analyzer":"my_analyzer"
                },
                "Students":{
                    "type":"integer"
                },
                "Undergraduates":{
                    "type":"integer"
                },
                "Postgraduates":{
                    "type":"integer"
                },
                "Url":{
                    "type":"text",
                    "fields":{
                        "keyword":{
                            "type":"keyword"
                        }
                    },
                    "analyzer":"my_analyzer"
                },
                "Location":{
                    "type":"text",
                    "fields":{
                        "keyword":{
                            "type":"keyword"
                        }
                    },
                    "analyzer":"my_analyzer"
                },
                "Established":{
                    "type":"integer"
                },
                "Number of students":{
                    "type":"integer"
                },
                "Tuition fee":{
                    "type":"integer"
                },
                "Degree powers":{
                    "type":"text",
                    "fields":{
                        "keyword":{
                            "type":"keyword"
                        }
                    },
                    "analyzer":"my_analyzer"
                }
            }
        }
    }
}